name: Continuous integration
on:
  workflow_call:

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  # Used to select the version of Redot to run the tests with.
  REDOT_TEST_VERSION: 4.3-stable

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: üêß Linux (GCC)
            os: ubuntu-20.04
            platform: linux
            artifact-name: redot-cpp-linux-glibc2.27-x86_64-release
            artifact-path: bin/libredot-cpp.linux.template_release.x86_64.a
            run-tests: true
            cache-name: linux-x86_64

          - name: üêß Linux (GCC, Double Precision)
            os: ubuntu-20.04
            platform: linux
            artifact-name: redot-cpp-linux-glibc2.27-x86_64-double-release
            artifact-path: bin/libredot-cpp.linux.template_release.double.x86_64.a
            flags: precision=double
            run-tests: false
            cache-name: linux-x86_64-f64

          - name: üèÅ Windows (x86_64, MSVC)
            os: windows-2019
            platform: windows
            artifact-name: redot-cpp-windows-msvc2019-x86_64-release
            artifact-path: bin/libredot-cpp.windows.template_release.x86_64.lib
            run-tests: false
            cache-name: windows-x86_64-msvc

          - name: üèÅ Windows (x86_64, MinGW)
            os: windows-2019
            platform: windows
            artifact-name: redot-cpp-linux-mingw-x86_64-release
            artifact-path: bin/libredot-cpp.windows.template_release.x86_64.a
            flags: use_mingw=yes
            run-tests: false
            cache-name: windows-x86_64-mingw

          - name: üçé macOS (universal)
            os: macos-latest
            platform: macos
            artifact-name: redot-cpp-macos-universal-release
            artifact-path: bin/libredot-cpp.macos.template_release.universal.a
            flags: arch=universal
            run-tests: false
            cache-name: macos-universal

          - name: ü§ñ Android (arm64)
            os: ubuntu-20.04
            platform: android
            artifact-name: redot-cpp-android-arm64-release
            artifact-path: bin/libredot-cpp.android.template_release.arm64.a
            flags: arch=arm64
            run-tests: false
            cache-name: android-arm64

          - name: üçè iOS (arm64)
            os: macos-latest
            platform: ios
            artifact-name: redot-cpp-ios-arm64-release
            artifact-path: bin/libredot-cpp.ios.template_release.arm64.a
            flags: arch=arm64
            run-tests: false
            cache-name: ios-arm64

          - name: üåê Web (wasm32)
            os: ubuntu-20.04
            platform: web
            artifact-name: redot-cpp-web-wasm32-release
            artifact-path: bin/libredot-cpp.web.template_release.wasm32.a
            run-tests: false
            cache-name: web-wasm32

    env:
      SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
      EM_VERSION: 3.1.39

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Redot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup godot-cpp
        uses: ./.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}
          windows-compiler: ${{ contains(matrix.flags, 'use_mingw=yes') && 'mingw' || 'msvc' }}

      - name: Generate redot-cpp sources only
        run: |
          scons platform=${{ matrix.platform }} verbose=yes build_library=no ${{ matrix.flags }}
          scons -c

      - name: Build redot-cpp (debug)
        run: |
          scons platform=${{ matrix.platform }} verbose=yes target=template_debug ${{ matrix.flags }}

      - name: Build test without rebuilding redot-cpp (debug)
        run: |
          cd test
          scons platform=${{ matrix.platform }} verbose=yes target=template_debug ${{ matrix.flags }} build_library=no

      - name: Build test and redot-cpp (release)
        run: |
          cd test
          scons platform=${{ matrix.platform }} verbose=yes target=template_release ${{ matrix.flags }}

      - name: Save Redot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Download latest Redot artifacts
        uses: dsnopek/action-download-artifact@1322f74e2dac9feed2ee76a32d9ae1ca3b4cf4e9
        if: matrix.run-tests && env.REDOT_TEST_VERSION == 'master'
        with:
          repo: Redot-Engine/redot-engine
          branch: master
          event: push
          workflow: linux_builds.yml
          workflow_conclusion: success
          name: linux-editor-mono
          search_artifacts: true
          check_artifacts: true
          ensure_latest: true
          path: redot-artifacts

      - name: Prepare Redot artifacts for testing
        if: matrix.run-tests && env.REDOT_TEST_VERSION == 'master'
        run: |
          chmod +x ./redot-artifacts/redot.linuxbsd.editor.x86_64.mono
          echo "REDOT=$(pwd)/redot-artifacts/redot.linuxbsd.editor.x86_64.mono" >> $GITHUB_ENV

      - name: Download requested Redot version for testing
        if: matrix.run-tests && env.REDOT_TEST_VERSION != 'master'
        run: |
          wget "https://github.com/Redot-Engine/redot-engine/releases/download/redot-${REDOT_TEST_VERSION}/Redot_v${REDOT_TEST_VERSION}_linux.x86_64.zip" -O Redot.zip
          unzip -a Redot.zip
          chmod +x "Redot_v${REDOT_TEST_VERSION}_linux.x86_64"
          echo "REDOT=$(pwd)/Redot_v${REDOT_TEST_VERSION}_linux.x86_64" >> $GITHUB_ENV

      - name: Run tests
        if: matrix.run-tests
        run: |
          $REDOT --headless --version
          cd test
          # Need to run the editor so .godot is generated... but it crashes! Ignore that :-)
          (cd project && (timeout 30 $REDOT --import --headless >/dev/null 2>&1 || true))
          ./run-tests.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          if-no-files-found: error

  linux-cmake:
    name: üêß Build (Linux, GCC, CMake)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config cmake

      - name: Build redot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j $(nproc) VERBOSE=1

      - name: Build test GDExtension library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../redot-headers" -DCPP_BINDINGS_PATH=".." .
          make -j $(nproc) VERBOSE=1

  linux-cmake-ninja:
    name: üêß Build (Linux, GCC, CMake Ninja)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config cmake ninja-build

      - name: Build redot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja .
          cmake --build . -j $(nproc) --verbose

      - name: Build test GDExtension library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../redot-headers" -DCPP_BINDINGS_PATH=".." -GNinja .
          cmake --build . -j $(nproc) --verbose

  windows-msvc-cmake:
    name: üèÅ Build (Windows, MSVC, CMake)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build redot-cpp
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" .
          cmake --build . --verbose --config Release

      - name: Build test GDExtension library
        run: |
          cd test && cmake -DCMAKE_BUILD_TYPE=Release -DGODOT_HEADERS_PATH="../redot-headers" -DCPP_BINDINGS_PATH=".." -G"Visual Studio 16 2019" .
          cmake --build . --verbose --config Release
